name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Install latest corepack
        run: npm install -g corepack
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - name: Fix lint issues
        run: pnpm run lint:fix
      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: 'chore: 🚨 apply automated lint fixes'
