name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup pnpm env 🏗
        uses: pnpm/action-setup@v6.0.10

      - name: Setup node env 🏗
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: pnpm

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install

      - name: Run linter 👀
        run: pnpm lint

      # - name: Run tests 🧪
      #   run: npm run test

      - name: Build app 🏗️
        run: pnpm build
